language: cpp
os:
  - linux
  - osx
compiler:
  #- gcc
  - clang
matrix:
  exclude:
    - os: osx
      compiler: gcc # Don't do a gcc build on OSX
cache: apt
install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then .travis/setup_linux.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then .travis/setup_osx.sh ; fi
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then cmake -DCMAKE_PREFIX_PATH=/opt/qt54/lib/cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Debug . && make -j4 ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Release . && make -j4 ; fi
  - make check
after_success:
  # Build the OS X installer.
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then cd osx && ./createbundle.sh .. && cd .. ; fi
# Update OS X installer to Github when building a tag.
deploy:
  provider: releases
  api-key:
    secure: qplvDHVFNYIaWeNPIiEvTM1Uolwg90kG9kchjauq7Srvf8pGjmQ9478gYEMsDTn3wyxPAAFZxIMfiXPwuCvFahk0mTFi2bkoGAeG72lQcO9gr2CF9Lpa7XK9tBDuzqmcrxfIxRdOGgD5zV/hnqz8jYQAgkhhVfi8aqqscXMYFL0=
  file: osx/powertabeditor.app.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_OS_NAME = osx"
